# FILE: docker-compose.prod.yml
# This file is used for production-like deployments, pulling pre-built images.

services:
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file: .env
    networks:
      - edi_network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - KEYCLOAK_DB_SCHEMA=${KEYCLOAK_DB_SCHEMA}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
      - ./backend/scripts/init-keycloak-db.sh:/docker-entrypoint-initdb.d/init-keycloak-db.sh
    networks:
      - edi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: ${DOCKERHUB_USERNAME}/edi-lens-backend:${BACKEND_IMAGE_TAG:-latest}
    restart: always
    depends_on:
      - db
      - keycloak
    volumes:
      - ./backend/data/edi_schemas:/var/edi_lens/schemas
    env_file: .env
    networks:
      - edi_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    depends_on:
      - db
    environment:
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USER}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL_HOST=db
      - KC_DB_URL_DATABASE=${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_DB_SCHEMA=${KEYCLOAK_DB_SCHEMA}
      - JAVA_OPTS_APPEND=-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled -Xms64m -Xmx512m
    networks:
      - edi_network
    command: start-dev

  admin-ui:
    image: ${DOCKERHUB_USERNAME}/edi-lens-ui:${UI_IMAGE_TAG:-latest}
    restart: always
    depends_on:
      - backend
    networks:
      - edi_network

volumes:
  caddy_data:
  caddy_config:
  postgres-data:

networks:
  edi_network:
    name: edi-lens_edi_network # Explicitly name the network
    driver: bridge