# FILE: docker-compose.run.yml

services:
  run-command:
    image: ${RUN_IMAGE}
    # working_dir is inherited from the image, but being explicit doesn't hurt.
    working_dir: /home/appuser/app
    env_file:
      - .env
    # We will let the main prod.yml file handle network attachment.
    # The 'run' command will attach this to the default project network.