"""feat: add SFTP configuration and file processing tables

Revision ID: 0e0e8a1996ec
Revises: 70710a86e3a2
Create Date: 2025-08-02 20:26:33.292523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0e8a1996ec'
down_revision: Union[str, Sequence[str], None] = '70710a86e3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types first
    source_type_enum = sa.Enum('API', 'SFTP', 'MANUAL', name='sourcetype')
    source_type_enum.create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cron_expression', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='_schedule_name_uc'),
    schema='public'
    )
    op.create_index(op.f('ix_public_processing_schedules_id'), 'processing_schedules', ['id'], unique=False, schema='public')
    op.create_table('sftp_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('sftp_enabled', sa.Boolean(), nullable=False),
    sa.Column('sftp_username', sa.String(), nullable=False),
    sa.Column('authentication_type', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('ssh_public_key', sa.Text(), nullable=True),
    sa.Column('inbound_directory', sa.String(), nullable=False),
    sa.Column('outbound_directory', sa.String(), nullable=False),
    sa.Column('archive_directory', sa.String(), nullable=True),
    sa.Column('file_name_patterns', sa.Text(), nullable=True),
    sa.Column('poll_schedule_id', sa.Integer(), nullable=True),
    sa.Column('poll_enabled', sa.Boolean(), nullable=False),
    sa.Column('response_filename_template', sa.String(), nullable=True),
    sa.Column('response_filename_regex', sa.String(), nullable=True),
    sa.Column('response_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('max_file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['public.trading_partners.id'], ),
    sa.ForeignKeyConstraint(['poll_schedule_id'], ['public.processing_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'partner_id', name='_tenant_partner_sftp_uc'),
    schema='public'
    )
    op.create_index(op.f('ix_public_sftp_configurations_id'), 'sftp_configurations', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sftp_configurations_tenant_id'), 'sftp_configurations', ['tenant_id'], unique=False, schema='public')
    op.create_table('file_processing_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('sftp_config_id', sa.Integer(), nullable=False),
    sa.Column('validation_transaction_id', sa.UUID(), nullable=True),
    sa.Column('source_filename', sa.String(), nullable=False),
    sa.Column('source_directory', sa.String(), nullable=False),
    sa.Column('source_file_size', sa.BigInteger(), nullable=True),
    sa.Column('source_file_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_filename', sa.String(), nullable=True),
    sa.Column('response_directory', sa.String(), nullable=True),
    sa.Column('response_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['public.trading_partners.id'], ),
    sa.ForeignKeyConstraint(['sftp_config_id'], ['public.sftp_configurations.id'], ),
    sa.ForeignKeyConstraint(['validation_transaction_id'], ['public.validation_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_file_processing_logs_tenant_id'), 'file_processing_logs', ['tenant_id'], unique=False, schema='public')
    op.add_column('validation_transactions', sa.Column('source_type', sa.Enum('API', 'SFTP', 'MANUAL', name='sourcetype'), nullable=False), schema='public')
    op.add_column('validation_transactions', sa.Column('source_partner_id', sa.Integer(), nullable=True), schema='public')
    op.add_column('validation_transactions', sa.Column('source_file_path', sa.String(), nullable=True), schema='public')
    op.add_column('validation_transactions', sa.Column('response_delivered', sa.Boolean(), nullable=False), schema='public')
    op.add_column('validation_transactions', sa.Column('response_delivery_attempts', sa.Integer(), nullable=False), schema='public')
    op.add_column('validation_transactions', sa.Column('response_delivered_at', sa.DateTime(timezone=True), nullable=True), schema='public')
    op.create_foreign_key(None, 'validation_transactions', 'trading_partners', ['source_partner_id'], ['id'], source_schema='public', referent_schema='public')
    
    # Insert default processing schedules
    processing_schedules_table = sa.table('processing_schedules',
        sa.column('name', sa.String),
        sa.column('description', sa.Text),
        sa.column('cron_expression', sa.String),
        sa.column('is_active', sa.Boolean),
        schema='public'
    )
    
    op.bulk_insert(processing_schedules_table, [
        {
            'name': 'Every 5 minutes',
            'description': 'Continuous polling every 5 minutes',
            'cron_expression': '*/5 * * * *',
            'is_active': True
        },
        {
            'name': 'Every 15 minutes', 
            'description': 'Every 15 minutes',
            'cron_expression': '*/15 * * * *',
            'is_active': True
        },
        {
            'name': 'Every hour',
            'description': 'Top of every hour',
            'cron_expression': '0 * * * *',
            'is_active': True
        },
        {
            'name': 'Business hours only',
            'description': 'Every 15 minutes, 9 AM - 5 PM, weekdays',
            'cron_expression': '*/15 9-17 * * MON-FRI',
            'is_active': True
        },
        {
            'name': 'Once daily at 9 AM',
            'description': 'Daily at 9:00 AM',
            'cron_expression': '0 9 * * *',
            'is_active': True
        },
        {
            'name': 'Manual only',
            'description': 'Disable automatic polling',
            'cron_expression': '',
            'is_active': True
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validation_transactions', schema='public', type_='foreignkey')
    op.drop_column('validation_transactions', 'response_delivered_at', schema='public')
    op.drop_column('validation_transactions', 'response_delivery_attempts', schema='public')
    op.drop_column('validation_transactions', 'response_delivered', schema='public')
    op.drop_column('validation_transactions', 'source_file_path', schema='public')
    op.drop_column('validation_transactions', 'source_partner_id', schema='public')
    op.drop_column('validation_transactions', 'source_type', schema='public')
    op.drop_index(op.f('ix_public_file_processing_logs_tenant_id'), table_name='file_processing_logs', schema='public')
    op.drop_table('file_processing_logs', schema='public')
    op.drop_index(op.f('ix_public_sftp_configurations_tenant_id'), table_name='sftp_configurations', schema='public')
    op.drop_index(op.f('ix_public_sftp_configurations_id'), table_name='sftp_configurations', schema='public')
    op.drop_table('sftp_configurations', schema='public')
    op.drop_index(op.f('ix_public_processing_schedules_id'), table_name='processing_schedules', schema='public')
    op.drop_table('processing_schedules', schema='public')
    
    # Drop enum types
    source_type_enum = sa.Enum('API', 'SFTP', 'MANUAL', name='sourcetype')
    source_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
