"""feat: replace rule overrides with specialized schema link

Revision ID: 35ed0fc3228c
Revises: 1acebb797b32
Create Date: 2025-08-02 02:37:58.222258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35ed0fc3228c'
down_revision: Union[str, Sequence[str], None] = '1acebb797b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_profile_rule_associations_id'), table_name='profile_rule_associations', schema='public')
    op.drop_table('profile_rule_associations', schema='public')
    op.drop_index(op.f('ix_public_rules_id'), table_name='rules', schema='public')
    op.drop_index(op.f('ix_public_rules_implementation_guide'), table_name='rules', schema='public')
    op.drop_index(op.f('ix_public_rules_rule_code'), table_name='rules', schema='public')
    op.drop_table('rules', schema='public')
    op.add_column('partner_profiles', sa.Column('validation_schema_name', sa.String(), nullable=True), schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_profiles', 'validation_schema_name', schema='public')
    op.create_table('rules',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"public".rules_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('rule_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('snip_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('implementation_guide', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('validation_logic', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='rules_pkey'),
    schema='public',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_public_rules_rule_code'), 'rules', ['rule_code'], unique=True, schema='public')
    op.create_index(op.f('ix_public_rules_implementation_guide'), 'rules', ['implementation_guide'], unique=False, schema='public')
    op.create_index(op.f('ix_public_rules_id'), 'rules', ['id'], unique=False, schema='public')
    op.create_table('profile_rule_associations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('override_severity', postgresql.ENUM('error', 'warning', 'info', name='severitylevel'), autoincrement=False, nullable=True),
    sa.Column('override_params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['public.partner_profiles.id'], name=op.f('profile_rule_associations_profile_id_fkey')),
    sa.ForeignKeyConstraint(['rule_id'], ['public.rules.id'], name=op.f('profile_rule_associations_rule_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_rule_associations_pkey')),
    schema='public'
    )
    op.create_index(op.f('ix_public_profile_rule_associations_id'), 'profile_rule_associations', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###
