"""refactor: remove obsolete processing_schedules table

Revision ID: 4af562f28ebe
Revises: fb427f5a424b
Create Date: 2025-08-09 17:34:27.024125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4af562f28ebe'
down_revision: Union[str, Sequence[str], None] = 'fb427f5a424b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_processing_schedules_id'), table_name='processing_schedules', schema='public')
    op.drop_table('processing_schedules', schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cron_expression', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('processing_schedules_pkey')),
    sa.UniqueConstraint('name', name=op.f('_schedule_name_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='public'
    )
    op.create_index(op.f('ix_public_processing_schedules_id'), 'processing_schedules', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###
