"""Add multi-tenant SFTP helper methods and configurations

This migration documents the implementation of multi-tenant SFTP functionality.
While no database schema changes were required, this version includes:

- Enhanced SftpConfiguration model with multi-tenant helper methods:
  * get_tenant_partner_username() - generates tenant_partner format usernames
  * get_partner_directory_path() - generates tenant-aware directory paths
  * get_inbound_directory_path() - generates tenant-specific inbound paths
  * get_outbound_directory_path() - generates tenant-specific outbound paths

- Multi-tenant SFTP server configuration:
  * Directory structure: /sftp/tenants/tenant-id/partner-name/{in,out}/
  * User management: tenant-id_partner-name username format
  * Complete tenant and partner isolation

- Enhanced file processing services:
  * FileDiscoveryService updated for multi-tenant structure
  * SftpFileProcessor supports tenant-aware file processing
  * Archive management with tenant-specific directories

Revision ID: 50a46f3ffa51
Revises: 0e0e8a1996ec
Create Date: 2025-08-03 01:56:06.657956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a46f3ffa51'
down_revision: Union[str, Sequence[str], None] = '0e0e8a1996ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
