"""feat: unify logs and simplify sftp config

Revision ID: fb427f5a424b
Revises: 60eea9d3c7db
Create Date: 2025-08-09 16:07:15.822711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb427f5a424b'
down_revision: Union[str, Sequence[str], None] = '60eea9d3c7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_file_processing_logs_tenant_id'), table_name='file_processing_logs', schema='public')
    op.drop_table('file_processing_logs', schema='public')
    op.drop_index(op.f('ix_public_sftp_configurations_id'), table_name='sftp_configurations', schema='public')
    op.drop_index(op.f('ix_public_sftp_configurations_tenant_id'), table_name='sftp_configurations', schema='public')
    op.drop_table('sftp_configurations', schema='public')
    op.add_column('trading_partners', sa.Column('sftp_enabled', sa.Boolean(), server_default='false', nullable=False), schema='public')
    op.add_column('trading_partners', sa.Column('sftp_username', sa.String(), nullable=True), schema='public')
    op.create_unique_constraint(None, 'trading_partners', ['sftp_username'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trading_partners', schema='public', type_='unique')
    op.drop_column('trading_partners', 'sftp_username', schema='public')
    op.drop_column('trading_partners', 'sftp_enabled', schema='public')
    op.create_table('sftp_configurations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"public".sftp_configurations_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sftp_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sftp_username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('authentication_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ssh_public_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inbound_directory', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('outbound_directory', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_name_patterns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('poll_schedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poll_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('response_filename_template', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response_filename_regex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response_timeout_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['public.trading_partners.id'], name='sftp_configurations_partner_id_fkey'),
    sa.ForeignKeyConstraint(['poll_schedule_id'], ['public.processing_schedules.id'], name='sftp_configurations_poll_schedule_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sftp_configurations_pkey'),
    sa.UniqueConstraint('tenant_id', 'partner_id', name='_tenant_partner_sftp_uc', postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='public',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_public_sftp_configurations_tenant_id'), 'sftp_configurations', ['tenant_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sftp_configurations_id'), 'sftp_configurations', ['id'], unique=False, schema='public')
    op.create_table('file_processing_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sftp_config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('validation_transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_directory', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_file_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('source_file_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processing_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processing_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('locked_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('lock_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('response_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response_directory', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response_delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('response_delivery_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('archive_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['public.trading_partners.id'], name=op.f('file_processing_logs_partner_id_fkey')),
    sa.ForeignKeyConstraint(['sftp_config_id'], ['public.sftp_configurations.id'], name=op.f('file_processing_logs_sftp_config_id_fkey')),
    sa.ForeignKeyConstraint(['validation_transaction_id'], ['public.validation_transactions.id'], name=op.f('file_processing_logs_validation_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('file_processing_logs_pkey')),
    schema='public'
    )
    op.create_index(op.f('ix_public_file_processing_logs_tenant_id'), 'file_processing_logs', ['tenant_id'], unique=False, schema='public')
    # ### end Alembic commands ###
