"""Add Registry-first models for NiFi integration

Revision ID: 1fb352bda567
Revises: add_ui_config_fields
Create Date: 2025-08-30 04:36:40.135360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fb352bda567'
down_revision: Union[str, Sequence[str], None] = 'add_ui_config_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registry_buckets',
    sa.Column('bucket_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'GLOBAL' AND tenant_id IS NULL) OR (scope = 'TENANT' AND tenant_id IS NOT NULL)", name='bucket_tenant_scope_consistency'),
    sa.CheckConstraint("scope IN ('GLOBAL', 'TENANT')", name='valid_bucket_scope'),
    sa.PrimaryKeyConstraint('bucket_id'),
    schema='public'
    )
    op.create_table('registry_templates',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('bucket_id', sa.UUID(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(scope = 'GLOBAL' AND tenant_id IS NULL) OR (scope = 'TENANT' AND tenant_id IS NOT NULL)", name='tenant_scope_consistency'),
    sa.CheckConstraint("scope IN ('GLOBAL', 'TENANT')", name='valid_scope'),
    sa.PrimaryKeyConstraint('template_id'),
    schema='public'
    )
    op.create_table('workflow_instances',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nifi_process_group_id', sa.UUID(), nullable=True),
    sa.Column('nifi_parameter_context_id', sa.UUID(), nullable=True),
    sa.Column('nifi_registry_client_id', sa.String(), nullable=True),
    sa.Column('version_control_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('CREATED', 'DEPLOYED', 'RUNNING', 'STOPPED', 'ERROR', 'DELETED')", name='valid_status'),
    sa.PrimaryKeyConstraint('workflow_id'),
    schema='public'
    )
    op.drop_index(op.f('idx_template_usage_action'), table_name='template_usage', schema='public')
    op.drop_index(op.f('idx_template_usage_template'), table_name='template_usage', schema='public')
    op.drop_index(op.f('idx_template_usage_tenant'), table_name='template_usage', schema='public')
    op.drop_constraint(op.f('fk_template_usage_template_id'), 'template_usage', schema='public', type_='foreignkey')
    op.drop_index(op.f('idx_template_versions_current'), table_name='template_versions', schema='public', postgresql_where='(is_current = true)')
    op.drop_index(op.f('idx_template_versions_template'), table_name='template_versions', schema='public')
    op.drop_constraint(op.f('fk_template_versions_template_id'), 'template_versions', schema='public', type_='foreignkey')
    op.alter_column('workflow_templates', 'ui_configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='WorkflowUIConfiguration for dynamic interface generation',
               existing_nullable=True,
               schema='public')
    op.alter_column('workflow_templates', 'input_specifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Supported input types and constraints',
               existing_nullable=True,
               schema='public')
    op.alter_column('workflow_templates', 'output_specifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Expected output definitions',
               existing_nullable=True,
               schema='public')
    op.alter_column('workflow_templates', 'processing_capabilities',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Processing capabilities (e.g., validation, transformation)',
               existing_nullable=True,
               schema='public')
    op.alter_column('workflow_templates', 'supported_file_types',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Supported file extensions',
               existing_nullable=True,
               schema='public')
    op.alter_column('workflow_templates', 'use_cases',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Common use cases for this template',
               existing_nullable=True,
               schema='public')
    op.alter_column('workflow_templates', 'industry_tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Industry-specific tags',
               existing_nullable=True,
               schema='public')
    op.drop_index(op.f('idx_templates_based_on'), table_name='workflow_templates', schema='public')
    op.drop_index(op.f('idx_templates_category'), table_name='workflow_templates', schema='public')
    op.drop_index(op.f('idx_templates_featured'), table_name='workflow_templates', schema='public', postgresql_where='(is_featured = true)')
    op.drop_index(op.f('idx_templates_scope'), table_name='workflow_templates', schema='public')
    op.drop_index(op.f('idx_templates_status'), table_name='workflow_templates', schema='public')
    op.drop_index(op.f('idx_templates_tenant'), table_name='workflow_templates', schema='public')
    op.drop_constraint(op.f('fk_workflow_templates_based_on'), 'workflow_templates', schema='public', type_='foreignkey')
    op.drop_index(op.f('idx_workflows_status'), table_name='workflows', schema='public')
    op.drop_index(op.f('idx_workflows_tags'), table_name='workflows', schema='public', postgresql_using='gin')
    op.drop_index(op.f('idx_workflows_template'), table_name='workflows', schema='public')
    op.drop_index(op.f('idx_workflows_tenant'), table_name='workflows', schema='public')
    op.drop_constraint(op.f('fk_workflows_template_id'), 'workflows', schema='public', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_workflows_template_id'), 'workflows', 'workflow_templates', ['template_id'], ['template_id'], source_schema='public', referent_schema='public')
    op.create_index(op.f('idx_workflows_tenant'), 'workflows', ['tenant_id'], unique=False, schema='public')
    op.create_index(op.f('idx_workflows_template'), 'workflows', ['template_id'], unique=False, schema='public')
    op.create_index(op.f('idx_workflows_tags'), 'workflows', ['tags'], unique=False, schema='public', postgresql_using='gin')
    op.create_index(op.f('idx_workflows_status'), 'workflows', ['status'], unique=False, schema='public')
    op.create_foreign_key(op.f('fk_workflow_templates_based_on'), 'workflow_templates', 'workflow_templates', ['based_on'], ['template_id'], source_schema='public', referent_schema='public')
    op.create_index(op.f('idx_templates_tenant'), 'workflow_templates', ['tenant_id'], unique=False, schema='public')
    op.create_index(op.f('idx_templates_status'), 'workflow_templates', ['status'], unique=False, schema='public')
    op.create_index(op.f('idx_templates_scope'), 'workflow_templates', ['scope'], unique=False, schema='public')
    op.create_index(op.f('idx_templates_featured'), 'workflow_templates', ['is_featured'], unique=False, schema='public', postgresql_where='(is_featured = true)')
    op.create_index(op.f('idx_templates_category'), 'workflow_templates', ['category'], unique=False, schema='public')
    op.create_index(op.f('idx_templates_based_on'), 'workflow_templates', ['based_on'], unique=False, schema='public')
    op.alter_column('workflow_templates', 'industry_tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment='Industry-specific tags',
               existing_nullable=True,
               schema='public')
    op.alter_column('workflow_templates', 'use_cases',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment='Common use cases for this template',
               existing_nullable=True,
               schema='public')
    op.alter_column('workflow_templates', 'supported_file_types',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment='Supported file extensions',
               existing_nullable=True,
               schema='public')
    op.alter_column('workflow_templates', 'processing_capabilities',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment='Processing capabilities (e.g., validation, transformation)',
               existing_nullable=True,
               schema='public')
    op.alter_column('workflow_templates', 'output_specifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Expected output definitions',
               existing_nullable=True,
               schema='public')
    op.alter_column('workflow_templates', 'input_specifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Supported input types and constraints',
               existing_nullable=True,
               schema='public')
    op.alter_column('workflow_templates', 'ui_configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='WorkflowUIConfiguration for dynamic interface generation',
               existing_nullable=True,
               schema='public')
    op.create_foreign_key(op.f('fk_template_versions_template_id'), 'template_versions', 'workflow_templates', ['template_id'], ['template_id'], source_schema='public', referent_schema='public')
    op.create_index(op.f('idx_template_versions_template'), 'template_versions', ['template_id'], unique=False, schema='public')
    op.create_index(op.f('idx_template_versions_current'), 'template_versions', ['template_id'], unique=False, schema='public', postgresql_where='(is_current = true)')
    op.create_foreign_key(op.f('fk_template_usage_template_id'), 'template_usage', 'workflow_templates', ['template_id'], ['template_id'], source_schema='public', referent_schema='public')
    op.create_index(op.f('idx_template_usage_tenant'), 'template_usage', ['tenant_id'], unique=False, schema='public')
    op.create_index(op.f('idx_template_usage_template'), 'template_usage', ['template_id'], unique=False, schema='public')
    op.create_index(op.f('idx_template_usage_action'), 'template_usage', ['action'], unique=False, schema='public')
    op.drop_table('workflow_instances', schema='public')
    op.drop_table('registry_templates', schema='public')
    op.drop_table('registry_buckets', schema='public')
    # ### end Alembic commands ###
