"""add knowledge base tables

Revision ID: 4b17c91c6f65
Revises: 9ce181cc3da7
Create Date: 2025-07-16 05:14:54.063480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b17c91c6f65'
down_revision: Union[str, Sequence[str], None] = '9ce181cc3da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='e.g., Health Care Claim: Professional (X222A1)'),
    sa.Column('version', sa.String(), nullable=False, comment='e.g., 005010X222A1'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_index(op.f('ix_public_kb_guides_id'), 'kb_guides', ['id'], unique=False, schema='public')
    op.create_table('kb_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.Enum('GUIDE', 'LOOP', 'SEGMENT', 'ELEMENT', 'COMPOSITE', 'RULE', name='nodetype'), nullable=False),
    sa.Column('node_key', sa.String(), nullable=False, comment='e.g., 2010AA.NM1.NM102'),
    sa.Column('name', sa.String(), nullable=False, comment='e.g., Billing Provider Name'),
    sa.Column('raw_text', sa.Text(), nullable=False, comment='The full text content of this specific node.'),
    sa.ForeignKeyConstraint(['guide_id'], ['public.kb_guides.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['public.kb_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_id', 'node_key', name='_guide_node_key_uc'),
    schema='public'
    )
    op.create_index(op.f('ix_public_kb_nodes_id'), 'kb_nodes', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_kb_nodes_node_key'), 'kb_nodes', ['node_key'], unique=False, schema='public')
    op.create_index(op.f('ix_public_kb_nodes_parent_id'), 'kb_nodes', ['parent_id'], unique=False, schema='public')
    op.create_table('kb_node_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('pinecone_vector_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['public.kb_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_kb_node_vectors_id'), 'kb_node_vectors', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_kb_node_vectors_pinecone_vector_id'), 'kb_node_vectors', ['pinecone_vector_id'], unique=True, schema='public')
    op.drop_constraint(op.f('partner_profiles_partner_id_fkey'), 'partner_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'partner_profiles', 'trading_partners', ['partner_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('profile_criteria_profile_id_fkey'), 'profile_criteria', type_='foreignkey')
    op.create_foreign_key(None, 'profile_criteria', 'partner_profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('profile_rule_associations_rule_id_fkey'), 'profile_rule_associations', type_='foreignkey')
    op.drop_constraint(op.f('profile_rule_associations_profile_id_fkey'), 'profile_rule_associations', type_='foreignkey')
    op.create_foreign_key(None, 'profile_rule_associations', 'rules', ['rule_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'profile_rule_associations', 'partner_profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_rule_associations', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'profile_rule_associations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('profile_rule_associations_profile_id_fkey'), 'profile_rule_associations', 'partner_profiles', ['profile_id'], ['id'])
    op.create_foreign_key(op.f('profile_rule_associations_rule_id_fkey'), 'profile_rule_associations', 'rules', ['rule_id'], ['id'])
    op.drop_constraint(None, 'profile_criteria', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('profile_criteria_profile_id_fkey'), 'profile_criteria', 'partner_profiles', ['profile_id'], ['id'])
    op.drop_constraint(None, 'partner_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('partner_profiles_partner_id_fkey'), 'partner_profiles', 'trading_partners', ['partner_id'], ['id'])
    op.drop_index(op.f('ix_public_kb_node_vectors_pinecone_vector_id'), table_name='kb_node_vectors', schema='public')
    op.drop_index(op.f('ix_public_kb_node_vectors_id'), table_name='kb_node_vectors', schema='public')
    op.drop_table('kb_node_vectors', schema='public')
    op.drop_index(op.f('ix_public_kb_nodes_parent_id'), table_name='kb_nodes', schema='public')
    op.drop_index(op.f('ix_public_kb_nodes_node_key'), table_name='kb_nodes', schema='public')
    op.drop_index(op.f('ix_public_kb_nodes_id'), table_name='kb_nodes', schema='public')
    op.drop_table('kb_nodes', schema='public')
    op.drop_index(op.f('ix_public_kb_guides_id'), table_name='kb_guides', schema='public')
    op.drop_table('kb_guides', schema='public')
    # ### end Alembic commands ###
