"""refactor: remove static archive_directory from sftp_configurations

Revision ID: 60eea9d3c7db
Revises: 7a095c351744
Create Date: 2025-08-09 15:16:20.141281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60eea9d3c7db'
down_revision: Union[str, Sequence[str], None] = '7a095c351744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sftp_configurations', 'archive_directory', schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sftp_configurations', sa.Column('archive_directory', sa.VARCHAR(), autoincrement=False, nullable=True), schema='public')
    # ### end Alembic commands ###
