"""feat: make validation_schema_name required on profiles and remove implementation_guide

Revision ID: 6e5197e41257
Revises: 4af562f28ebe
Create Date: 2025-08-09 18:44:28.405633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5197e41257'
down_revision: Union[str, Sequence[str], None] = '4af562f28ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_profiles', 'validation_schema_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='public')
    op.drop_index(op.f('ix_public_partner_profiles_implementation_guide'), table_name='partner_profiles', schema='public')
    op.create_index(op.f('ix_public_partner_profiles_validation_schema_name'), 'partner_profiles', ['validation_schema_name'], unique=False, schema='public')
    op.drop_column('partner_profiles', 'implementation_guide', schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_profiles', sa.Column('implementation_guide', sa.VARCHAR(), autoincrement=False, nullable=False), schema='public')
    op.drop_index(op.f('ix_public_partner_profiles_validation_schema_name'), table_name='partner_profiles', schema='public')
    op.create_index(op.f('ix_public_partner_profiles_implementation_guide'), 'partner_profiles', ['implementation_guide'], unique=False, schema='public')
    op.alter_column('partner_profiles', 'validation_schema_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='public')
    # ### end Alembic commands ###
