"""Create initial tables

Revision ID: 6fd4f6828a3c
Revises: 
Create Date: 2025-07-04 00:06:13.012359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd4f6828a3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('snip_level', sa.Integer(), nullable=True),
    sa.Column('implementation_guide', sa.String(), nullable=False),
    sa.Column('validation_logic', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_index(op.f('ix_rules_implementation_guide'), 'rules', ['implementation_guide'], unique=False)
    op.create_index(op.f('ix_rules_rule_code'), 'rules', ['rule_code'], unique=True)
    op.create_table('trading_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('edi_sender_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edi_sender_id'),
    sa.UniqueConstraint('name', name='uq_partner_name')
    )
    op.create_index(op.f('ix_trading_partners_id'), 'trading_partners', ['id'], unique=False)
    op.create_index(op.f('ix_trading_partners_name'), 'trading_partners', ['name'], unique=True)
    op.create_table('partner_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('implementation_guide', sa.String(), nullable=False),
    sa.Column('snip_level_enabled', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['trading_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_configurations_id'), 'partner_configurations', ['id'], unique=False)
    op.create_table('partner_rule_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('override_action', sa.String(), nullable=False),
    sa.Column('modified_params', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['partner_configurations.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_rule_overrides_id'), 'partner_rule_overrides', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_rule_overrides_id'), table_name='partner_rule_overrides')
    op.drop_table('partner_rule_overrides')
    op.drop_index(op.f('ix_partner_configurations_id'), table_name='partner_configurations')
    op.drop_table('partner_configurations')
    op.drop_index(op.f('ix_trading_partners_name'), table_name='trading_partners')
    op.drop_index(op.f('ix_trading_partners_id'), table_name='trading_partners')
    op.drop_table('trading_partners')
    op.drop_index(op.f('ix_rules_rule_code'), table_name='rules')
    op.drop_index(op.f('ix_rules_implementation_guide'), table_name='rules')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_table('rules')
    # ### end Alembic commands ###
