"""feat: add validation_transactions table

Revision ID: 70710a86e3a2
Revises: 35ed0fc3228c
Create Date: 2025-08-02 17:27:53.595843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70710a86e3a2'
down_revision: Union[str, Sequence[str], None] = '35ed0fc3228c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- THIS IS THE FIX ---
    # REMOVED all the op.create_table calls for tables that already exist
    # (audit_logs, trading_partners, partner_profiles, profile_criteria).
    
    # This migration should ONLY be responsible for creating the new table.
    op.create_table('validation_transactions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('partner_profile_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'COMPLETE', 'FAILED', name='validationstatus'), nullable=False),
        sa.Column('original_filename', sa.String(), nullable=False),
        sa.Column('request_object_key', sa.String(), nullable=False),
        sa.Column('ta1_object_key', sa.String(), nullable=True),
        sa.Column('response_999_object_key', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['partner_profile_id'], ['public.partner_profiles.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_validation_transactions_tenant_id'), 'validation_transactions', ['tenant_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_validation_transactions_user_id'), 'validation_transactions', ['user_id'], unique=False, schema='public')
    # --- END OF FIX ---
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- THIS IS THE FIX ---
    # The downgrade should ONLY drop the table this migration created.
    op.drop_index(op.f('ix_public_validation_transactions_user_id'), table_name='validation_transactions', schema='public')
    op.drop_index(op.f('ix_public_validation_transactions_tenant_id'), table_name='validation_transactions', schema='public')
    op.drop_table('validation_transactions', schema='public')
    # --- END OF FIX ---

    # ### end Alembic commands ###