"""feat: add validation_transactions table

Revision ID: 70710a86e3a2
Revises: 35ed0fc3228c
Create Date: 2025-08-02 17:27:53.595843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70710a86e3a2'
down_revision: Union[str, Sequence[str], None] = '35ed0fc3228c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='auditaction'), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_pk', sa.String(), nullable=True),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_audit_logs_id'), 'audit_logs', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_audit_logs_record_pk'), 'audit_logs', ['record_pk'], unique=False, schema='public')
    op.create_index(op.f('ix_public_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='public')
    op.create_table('trading_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='_tenant_partner_name_uc'),
    schema='public'
    )
    op.create_index(op.f('ix_public_trading_partners_id'), 'trading_partners', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_trading_partners_name'), 'trading_partners', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_trading_partners_tenant_id'), 'trading_partners', ['tenant_id'], unique=False, schema='public')
    op.create_table('partner_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('implementation_guide', sa.String(), nullable=False),
    sa.Column('validation_schema_name', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('snip_level_enabled', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['public.trading_partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_partner_profiles_id'), 'partner_profiles', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_partner_profiles_implementation_guide'), 'partner_profiles', ['implementation_guide'], unique=False, schema='public')
    op.create_index(op.f('ix_public_partner_profiles_tenant_id'), 'partner_profiles', ['tenant_id'], unique=False, schema='public')
    op.create_table('profile_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('field_source', sa.Enum('ISA', 'GS', 'FILENAME', name='fieldsource'), nullable=False),
    sa.Column('field_identifier', sa.String(), nullable=False),
    sa.Column('operator', sa.Enum('EQUALS', 'STARTS_WITH', 'CONTAINS', name='operator'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['public.partner_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_profile_criteria_id'), 'profile_criteria', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_profile_criteria_tenant_id'), 'profile_criteria', ['tenant_id'], unique=False, schema='public')
    op.create_table('validation_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('partner_profile_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETE', 'FAILED', name='validationstatus'), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('request_object_key', sa.String(), nullable=False),
    sa.Column('ta1_object_key', sa.String(), nullable=True),
    sa.Column('response_999_object_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_profile_id'], ['public.partner_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_validation_transactions_tenant_id'), 'validation_transactions', ['tenant_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_validation_transactions_user_id'), 'validation_transactions', ['user_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_validation_transactions_user_id'), table_name='validation_transactions', schema='public')
    op.drop_index(op.f('ix_public_validation_transactions_tenant_id'), table_name='validation_transactions', schema='public')
    op.drop_table('validation_transactions', schema='public')
    op.drop_index(op.f('ix_public_profile_criteria_tenant_id'), table_name='profile_criteria', schema='public')
    op.drop_index(op.f('ix_public_profile_criteria_id'), table_name='profile_criteria', schema='public')
    op.drop_table('profile_criteria', schema='public')
    op.drop_index(op.f('ix_public_partner_profiles_tenant_id'), table_name='partner_profiles', schema='public')
    op.drop_index(op.f('ix_public_partner_profiles_implementation_guide'), table_name='partner_profiles', schema='public')
    op.drop_index(op.f('ix_public_partner_profiles_id'), table_name='partner_profiles', schema='public')
    op.drop_table('partner_profiles', schema='public')
    op.drop_index(op.f('ix_public_trading_partners_tenant_id'), table_name='trading_partners', schema='public')
    op.drop_index(op.f('ix_public_trading_partners_name'), table_name='trading_partners', schema='public')
    op.drop_index(op.f('ix_public_trading_partners_id'), table_name='trading_partners', schema='public')
    op.drop_table('trading_partners', schema='public')
    op.drop_index(op.f('ix_public_audit_logs_user_id'), table_name='audit_logs', schema='public')
    op.drop_index(op.f('ix_public_audit_logs_tenant_id'), table_name='audit_logs', schema='public')
    op.drop_index(op.f('ix_public_audit_logs_table_name'), table_name='audit_logs', schema='public')
    op.drop_index(op.f('ix_public_audit_logs_request_id'), table_name='audit_logs', schema='public')
    op.drop_index(op.f('ix_public_audit_logs_record_pk'), table_name='audit_logs', schema='public')
    op.drop_index(op.f('ix_public_audit_logs_id'), table_name='audit_logs', schema='public')
    op.drop_table('audit_logs', schema='public')
    # ### end Alembic commands ###
