"""feat: simplify profile matching with filename patterns

Revision ID: 7a095c351744
Revises: 78b585c37c59
Create Date: 2025-08-09 14:00:41.283322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a095c351744'
down_revision: Union[str, Sequence[str], None] = '78b585c37c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_profile_criteria_id'), table_name='profile_criteria', schema='public')
    op.drop_index(op.f('ix_public_profile_criteria_tenant_id'), table_name='profile_criteria', schema='public')
    op.drop_table('profile_criteria', schema='public')
    op.add_column('partner_profiles', sa.Column('file_name_patterns', sa.Text(), nullable=True), schema='public')
    op.drop_index(op.f('ix_processing_logs_source'), table_name='processing_logs', schema='public')
    op.drop_index(op.f('ix_processing_logs_tenant_timestamp'), table_name='processing_logs', schema='public')
    op.drop_index(op.f('ix_processing_logs_validation_result'), table_name='processing_logs', schema='public')
    op.create_index(op.f('ix_public_processing_logs_id'), 'processing_logs', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_processing_logs_tenant_id'), 'processing_logs', ['tenant_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_processing_logs_tenant_id'), table_name='processing_logs', schema='public')
    op.drop_index(op.f('ix_public_processing_logs_id'), table_name='processing_logs', schema='public')
    op.create_index(op.f('ix_processing_logs_validation_result'), 'processing_logs', ['validation_result'], unique=False, schema='public')
    op.create_index(op.f('ix_processing_logs_tenant_timestamp'), 'processing_logs', ['tenant_id', 'timestamp'], unique=False, schema='public')
    op.create_index(op.f('ix_processing_logs_source'), 'processing_logs', ['source'], unique=False, schema='public')
    op.drop_column('partner_profiles', 'file_name_patterns', schema='public')
    op.create_table('profile_criteria',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_source', postgresql.ENUM('ISA', 'GS', 'FILENAME', name='fieldsource'), autoincrement=False, nullable=False),
    sa.Column('field_identifier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('operator', postgresql.ENUM('EQUALS', 'STARTS_WITH', 'CONTAINS', name='operator'), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['public.partner_profiles.id'], name=op.f('profile_criteria_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_criteria_pkey')),
    schema='public'
    )
    op.create_index(op.f('ix_public_profile_criteria_tenant_id'), 'profile_criteria', ['tenant_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_profile_criteria_id'), 'profile_criteria', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###
