"""Add tenant_id to core models

Revision ID: 9b87c7a5d4e3
Revises: aa1e2baf8a64
Create Date: 2025-07-05 06:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b87c7a5d4e3'
down_revision: Union[str, Sequence[str], None] = 'aa1e2baf8a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_profiles', sa.Column('tenant_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_partner_profiles_tenant_id'), 'partner_profiles', ['tenant_id'], unique=False)
    
    op.add_column('profile_criteria', sa.Column('tenant_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_profile_criteria_tenant_id'), 'profile_criteria', ['tenant_id'], unique=False)

    # Drop old unique constraint on trading_partners name
    op.drop_constraint('_partner_name_uc', 'trading_partners', type_='unique')
    op.add_column('trading_partners', sa.Column('tenant_id', sa.String(), nullable=False))
    # Create new composite unique constraint on (tenant_id, name)
    op.create_unique_constraint('_tenant_partner_name_uc', 'trading_partners', ['tenant_id', 'name'])
    op.create_index(op.f('ix_trading_partners_tenant_id'), 'trading_partners', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_partners_tenant_id'), table_name='trading_partners')
    op.drop_constraint('_tenant_partner_name_uc', 'trading_partners', type_='unique')
    op.drop_column('trading_partners', 'tenant_id')
    op.create_unique_constraint('_partner_name_uc', 'trading_partners', ['name'])

    op.drop_index(op.f('ix_profile_criteria_tenant_id'), table_name='profile_criteria')
    op.drop_column('profile_criteria', 'tenant_id')

    op.drop_index(op.f('ix_partner_profiles_tenant_id'), table_name='partner_profiles')
    op.drop_column('partner_profiles', 'tenant_id')
    # ### end Alembic commands ###