"""make audit_log record_pk nullable

Revision ID: 9c55f4be7519
Revises: 9b87c7a5d4e4
Create Date: 2025-07-06 01:04:22.946733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c55f4be7519'
down_revision: Union[str, Sequence[str], None] = '9b87c7a5d4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'record_pk',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_trading_partners_name'), table_name='trading_partners')
    op.create_index(op.f('ix_trading_partners_name'), 'trading_partners', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_partners_name'), table_name='trading_partners')
    op.create_index(op.f('ix_trading_partners_name'), 'trading_partners', ['name'], unique=True)
    op.alter_column('audit_logs', 'record_pk',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
