"""add schemas to all models

Revision ID: 9ce181cc3da7
Revises: 9c55f4be7519
Create Date: 2025-07-11 01:17:31.847441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce181cc3da7'
down_revision: Union[str, Sequence[str], None] = '9c55f4be7519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_pk'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.create_index(op.f('ix_public_audit_logs_id'), 'audit_logs', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_audit_logs_record_pk'), 'audit_logs', ['record_pk'], unique=False, schema='public')
    op.create_index(op.f('ix_public_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='public')
    op.drop_index(op.f('ix_partner_profiles_id'), table_name='partner_profiles')
    op.drop_index(op.f('ix_partner_profiles_implementation_guide'), table_name='partner_profiles')
    op.drop_index(op.f('ix_partner_profiles_tenant_id'), table_name='partner_profiles')
    op.create_index(op.f('ix_public_partner_profiles_id'), 'partner_profiles', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_partner_profiles_implementation_guide'), 'partner_profiles', ['implementation_guide'], unique=False, schema='public')
    op.create_index(op.f('ix_public_partner_profiles_tenant_id'), 'partner_profiles', ['tenant_id'], unique=False, schema='public')
    op.drop_constraint(op.f('partner_profiles_partner_id_fkey'), 'partner_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'partner_profiles', 'trading_partners', ['partner_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('ix_profile_criteria_id'), table_name='profile_criteria')
    op.drop_index(op.f('ix_profile_criteria_tenant_id'), table_name='profile_criteria')
    op.create_index(op.f('ix_public_profile_criteria_id'), 'profile_criteria', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_profile_criteria_tenant_id'), 'profile_criteria', ['tenant_id'], unique=False, schema='public')
    op.drop_constraint(op.f('profile_criteria_profile_id_fkey'), 'profile_criteria', type_='foreignkey')
    op.create_foreign_key(None, 'profile_criteria', 'partner_profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('ix_profile_rule_associations_id'), table_name='profile_rule_associations')
    op.create_index(op.f('ix_public_profile_rule_associations_id'), 'profile_rule_associations', ['id'], unique=False, schema='public')
    op.drop_constraint(op.f('profile_rule_associations_profile_id_fkey'), 'profile_rule_associations', type_='foreignkey')
    op.drop_constraint(op.f('profile_rule_associations_rule_id_fkey'), 'profile_rule_associations', type_='foreignkey')
    op.create_foreign_key(None, 'profile_rule_associations', 'rules', ['rule_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'profile_rule_associations', 'partner_profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_implementation_guide'), table_name='rules')
    op.drop_index(op.f('ix_rules_rule_code'), table_name='rules')
    op.create_index(op.f('ix_public_rules_id'), 'rules', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_rules_implementation_guide'), 'rules', ['implementation_guide'], unique=False, schema='public')
    op.create_index(op.f('ix_public_rules_rule_code'), 'rules', ['rule_code'], unique=True, schema='public')
    op.drop_index(op.f('ix_trading_partners_id'), table_name='trading_partners')
    op.drop_index(op.f('ix_trading_partners_name'), table_name='trading_partners')
    op.drop_index(op.f('ix_trading_partners_tenant_id'), table_name='trading_partners')
    op.create_index(op.f('ix_public_trading_partners_id'), 'trading_partners', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_trading_partners_name'), 'trading_partners', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_trading_partners_tenant_id'), 'trading_partners', ['tenant_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_trading_partners_tenant_id'), table_name='trading_partners', schema='public')
    op.drop_index(op.f('ix_public_trading_partners_name'), table_name='trading_partners', schema='public')
    op.drop_index(op.f('ix_public_trading_partners_id'), table_name='trading_partners', schema='public')
    op.create_index(op.f('ix_trading_partners_tenant_id'), 'trading_partners', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_trading_partners_name'), 'trading_partners', ['name'], unique=False)
    op.create_index(op.f('ix_trading_partners_id'), 'trading_partners', ['id'], unique=False)
    op.drop_index(op.f('ix_public_rules_rule_code'), table_name='rules', schema='public')
    op.drop_index(op.f('ix_public_rules_implementation_guide'), table_name='rules', schema='public')
    op.drop_index(op.f('ix_public_rules_id'), table_name='rules', schema='public')
    op.create_index(op.f('ix_rules_rule_code'), 'rules', ['rule_code'], unique=True)
    op.create_index(op.f('ix_rules_implementation_guide'), 'rules', ['implementation_guide'], unique=False)
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.drop_constraint(None, 'profile_rule_associations', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'profile_rule_associations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('profile_rule_associations_rule_id_fkey'), 'profile_rule_associations', 'rules', ['rule_id'], ['id'])
    op.create_foreign_key(op.f('profile_rule_associations_profile_id_fkey'), 'profile_rule_associations', 'partner_profiles', ['profile_id'], ['id'])
    op.drop_index(op.f('ix_public_profile_rule_associations_id'), table_name='profile_rule_associations', schema='public')
    op.create_index(op.f('ix_profile_rule_associations_id'), 'profile_rule_associations', ['id'], unique=False)
    op.drop_constraint(None, 'profile_criteria', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('profile_criteria_profile_id_fkey'), 'profile_criteria', 'partner_profiles', ['profile_id'], ['id'])
    op.drop_index(op.f('ix_public_profile_criteria_tenant_id'), table_name='profile_criteria', schema='public')
    op.drop_index(op.f('ix_public_profile_criteria_id'), table_name='profile_criteria', schema='public')
    op.create_index(op.f('ix_profile_criteria_tenant_id'), 'profile_criteria', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_profile_criteria_id'), 'profile_criteria', ['id'], unique=False)
    op.drop_constraint(None, 'partner_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('partner_profiles_partner_id_fkey'), 'partner_profiles', 'trading_partners', ['partner_id'], ['id'])
    op.drop_index(op.f('ix_public_partner_profiles_tenant_id'), table_name='partner_profiles', schema='public')
    op.drop_index(op.f('ix_public_partner_profiles_implementation_guide'), table_name='partner_profiles', schema='public')
    op.drop_index(op.f('ix_public_partner_profiles_id'), table_name='partner_profiles', schema='public')
    op.create_index(op.f('ix_partner_profiles_tenant_id'), 'partner_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_partner_profiles_implementation_guide'), 'partner_profiles', ['implementation_guide'], unique=False)
    op.create_index(op.f('ix_partner_profiles_id'), 'partner_profiles', ['id'], unique=False)
    op.drop_index(op.f('ix_public_audit_logs_user_id'), table_name='audit_logs', schema='public')
    op.drop_index(op.f('ix_public_audit_logs_tenant_id'), table_name='audit_logs', schema='public')
    op.drop_index(op.f('ix_public_audit_logs_table_name'), table_name='audit_logs', schema='public')
    op.drop_index(op.f('ix_public_audit_logs_request_id'), table_name='audit_logs', schema='public')
    op.drop_index(op.f('ix_public_audit_logs_record_pk'), table_name='audit_logs', schema='public')
    op.drop_index(op.f('ix_public_audit_logs_id'), table_name='audit_logs', schema='public')
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_pk'), 'audit_logs', ['record_pk'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###
