"""Add trading partner configuration tables

Revision ID: aa1e2baf8a64
Revises: 
Create Date: 2025-07-04 03:28:27.191940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1e2baf8a64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('snip_level', sa.Integer(), nullable=True),
    sa.Column('implementation_guide', sa.String(), nullable=False),
    sa.Column('validation_logic', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_index(op.f('ix_rules_implementation_guide'), 'rules', ['implementation_guide'], unique=False)
    op.create_index(op.f('ix_rules_rule_code'), 'rules', ['rule_code'], unique=True)
    op.create_table('trading_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='_partner_name_uc')
    )
    op.create_index(op.f('ix_trading_partners_id'), 'trading_partners', ['id'], unique=False)
    op.create_index(op.f('ix_trading_partners_name'), 'trading_partners', ['name'], unique=True)
    op.create_table('partner_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('implementation_guide', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('snip_level_enabled', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['trading_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_profiles_id'), 'partner_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_partner_profiles_implementation_guide'), 'partner_profiles', ['implementation_guide'], unique=False)
    op.create_table('profile_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('field_source', sa.Enum('ISA', 'GS', 'FILENAME', name='fieldsource'), nullable=False),
    sa.Column('field_identifier', sa.String(), nullable=False),
    sa.Column('operator', sa.Enum('EQUALS', 'STARTS_WITH', 'CONTAINS', name='operator'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['partner_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_criteria_id'), 'profile_criteria', ['id'], unique=False)
    op.create_table('profile_rule_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('override_severity', sa.Enum('error', 'warning', 'info', name='severitylevel'), nullable=True),
    sa.Column('override_params', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['partner_profiles.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_rule_associations_id'), 'profile_rule_associations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_rule_associations_id'), table_name='profile_rule_associations')
    op.drop_table('profile_rule_associations')
    op.drop_index(op.f('ix_profile_criteria_id'), table_name='profile_criteria')
    op.drop_table('profile_criteria')
    op.drop_index(op.f('ix_partner_profiles_implementation_guide'), table_name='partner_profiles')
    op.drop_index(op.f('ix_partner_profiles_id'), table_name='partner_profiles')
    op.drop_table('partner_profiles')
    op.drop_index(op.f('ix_trading_partners_name'), table_name='trading_partners')
    op.drop_index(op.f('ix_trading_partners_id'), table_name='trading_partners')
    op.drop_table('trading_partners')
    op.drop_index(op.f('ix_rules_rule_code'), table_name='rules')
    op.drop_index(op.f('ix_rules_implementation_guide'), table_name='rules')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_table('rules')
    # ### end Alembic commands ###
