"""Add undeployed_at field to workflows table

Revision ID: aca66c16089c
Revises: 1d2c87cd3490
Create Date: 2025-09-02 23:44:28.579796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aca66c16089c'
down_revision: Union[str, Sequence[str], None] = '1d2c87cd3490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_usage', schema='public')
    op.drop_table('template_versions', schema='public')
    op.drop_table('workflow_instances', schema='public')
    op.drop_table('workflow_templates', schema='public')
    op.add_column('workflows', sa.Column('undeployed_at', sa.DateTime(timezone=True), nullable=True), schema='public')
    op.drop_column('workflows', 'tags', schema='public')
    op.drop_column('workflows', 'deployment_method', schema='public')
    op.drop_column('workflows', 'flow_version', schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('flow_version', sa.INTEGER(), autoincrement=False, nullable=True), schema='public')
    op.add_column('workflows', sa.Column('deployment_method', sa.VARCHAR(), autoincrement=False, nullable=True), schema='public')
    op.add_column('workflows', sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True), schema='public')
    op.drop_column('workflows', 'undeployed_at', schema='public')
    op.create_table('workflow_templates',
    sa.Column('template_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('maintainer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('based_on', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), server_default=sa.text("'1.0'::character varying"), autoincrement=False, nullable=False),
    sa.Column('flow_definition', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('configuration_schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('deployment_method', sa.VARCHAR(), server_default=sa.text("'registry'::character varying"), autoincrement=False, nullable=False),
    sa.Column('nifi_registry_flow_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nifi_registry_bucket_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('documentation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deprecated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ui_configuration', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('input_specifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_specifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processing_capabilities', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('supported_file_types', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('use_cases', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('industry_tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.CheckConstraint("scope::text = 'GLOBAL'::text AND tenant_id IS NULL OR scope::text = 'TENANT'::text AND tenant_id IS NOT NULL", name=op.f('tenant_scope_consistency')),
    sa.CheckConstraint("scope::text = ANY (ARRAY['GLOBAL'::character varying, 'TENANT'::character varying]::text[])", name=op.f('valid_scope')),
    sa.PrimaryKeyConstraint('template_id', name=op.f('workflow_templates_pkey')),
    schema='public'
    )
    op.create_table('workflow_instances',
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('nifi_process_group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nifi_parameter_context_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nifi_registry_client_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version_control_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deployed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_stopped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['CREATED'::character varying, 'DEPLOYED'::character varying, 'RUNNING'::character varying, 'STOPPED'::character varying, 'ERROR'::character varying, 'DELETED'::character varying]::text[])", name=op.f('valid_status')),
    sa.ForeignKeyConstraint(['template_id'], ['public.registry_templates.template_id'], name=op.f('fk_workflow_instances_template_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflow_id', name=op.f('workflow_instances_pkey')),
    schema='public'
    )
    op.create_table('template_versions',
    sa.Column('version_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('flow_definition', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('configuration_schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('changes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_current', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deployment_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_id', name=op.f('template_versions_pkey')),
    sa.UniqueConstraint('template_id', 'version', name=op.f('uq_template_version'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='public'
    )
    op.create_table('template_usage',
    sa.Column('usage_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('configuration_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('usage_id', name=op.f('template_usage_pkey')),
    schema='public'
    )
    # ### end Alembic commands ###
