"""Add workflow templates and template management tables

Revision ID: da70c11e5c83
Revises: 8cc3281b6e57
Create Date: 2025-08-16 00:02:13.920019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da70c11e5c83'
down_revision: Union[str, Sequence[str], None] = '8cc3281b6e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove old trading partner/profile system (drop dependencies first)
    op.drop_constraint(op.f('fk_processing_logs_profile_id'), 'processing_logs', schema='public', type_='foreignkey')
    op.drop_column('processing_logs', 'profile_id', schema='public')
    op.drop_constraint(op.f('validation_transactions_source_partner_id_fkey'), 'validation_transactions', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('validation_transactions_partner_profile_id_fkey'), 'validation_transactions', schema='public', type_='foreignkey')
    op.drop_column('validation_transactions', 'partner_profile_id', schema='public')
    op.drop_column('validation_transactions', 'source_partner_id', schema='public')
    
    # Drop partner_profiles table and indexes
    op.drop_index(op.f('ix_public_partner_profiles_id'), table_name='partner_profiles', schema='public')
    op.drop_index(op.f('ix_public_partner_profiles_tenant_id'), table_name='partner_profiles', schema='public')
    op.drop_index(op.f('ix_public_partner_profiles_validation_schema_name'), table_name='partner_profiles', schema='public')
    op.drop_table('partner_profiles', schema='public')
    
    # Drop trading_partners table and indexes
    op.drop_index(op.f('ix_public_trading_partners_id'), table_name='trading_partners', schema='public')
    op.drop_index(op.f('ix_public_trading_partners_name'), table_name='trading_partners', schema='public')
    op.drop_index(op.f('ix_public_trading_partners_tenant_id'), table_name='trading_partners', schema='public')
    op.drop_table('trading_partners', schema='public')
    
    # Add new workflow template system
    
    # Create workflow_templates table
    op.create_table('workflow_templates',
        sa.Column('template_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('scope', sa.String(), nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=True),
        sa.Column('maintainer', sa.String(), nullable=True),
        sa.Column('based_on', sa.String(), nullable=True),
        sa.Column('version', sa.String(), nullable=False, server_default='1.0'),
        sa.Column('flow_definition', postgresql.JSONB(), nullable=False),
        sa.Column('configuration_schema', postgresql.JSONB(), nullable=False),
        sa.Column('deployment_method', sa.String(), nullable=False, server_default='registry'),
        sa.Column('nifi_registry_flow_id', sa.String(), nullable=True),
        sa.Column('nifi_registry_bucket_id', sa.String(), nullable=True),
        sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column('features', postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column('documentation', sa.Text(), nullable=True),
        sa.Column('examples', postgresql.JSONB(), nullable=True),
        sa.Column('status', sa.String(), nullable=False, server_default='ACTIVE'),
        sa.Column('is_featured', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('usage_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('NOW()')),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('NOW()')),
        sa.Column('deprecated_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('template_id'),
        sa.ForeignKeyConstraint(['based_on'], ['workflow_templates.template_id'], name='fk_workflow_templates_based_on'),
        sa.CheckConstraint("scope IN ('GLOBAL', 'TENANT')", name='valid_scope'),
        sa.CheckConstraint(
            "(scope = 'GLOBAL' AND tenant_id IS NULL) OR (scope = 'TENANT' AND tenant_id IS NOT NULL)", 
            name='tenant_scope_consistency'
        ),
        schema='public'
    )
    
    # Create template_versions table
    op.create_table('template_versions',
        sa.Column('version_id', postgresql.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('template_id', sa.String(), nullable=False),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('flow_definition', postgresql.JSONB(), nullable=False),
        sa.Column('configuration_schema', postgresql.JSONB(), nullable=False),
        sa.Column('changes', sa.Text(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('NOW()')),
        sa.Column('is_current', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('deployment_count', sa.Integer(), nullable=False, server_default='0'),
        sa.PrimaryKeyConstraint('version_id'),
        sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.template_id'], name='fk_template_versions_template_id'),
        sa.UniqueConstraint('template_id', 'version', name='uq_template_version'),
        schema='public'
    )
    
    # Create template_usage table
    op.create_table('template_usage',
        sa.Column('usage_id', postgresql.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('template_id', sa.String(), nullable=False),
        sa.Column('template_version', sa.String(), nullable=True),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('workflow_id', sa.String(), nullable=True),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('configuration_hash', sa.String(), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('NOW()')),
        sa.PrimaryKeyConstraint('usage_id'),
        sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.template_id'], name='fk_template_usage_template_id'),
        schema='public'
    )
    
    # Create workflows table
    op.create_table('workflows',
        sa.Column('workflow_id', postgresql.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column('template_id', sa.String(), nullable=False),
        sa.Column('configuration', postgresql.JSONB(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='ACTIVE'),
        sa.Column('nifi_process_group_id', sa.String(), nullable=True),
        sa.Column('nifi_parameter_context_id', sa.String(), nullable=True),
        sa.Column('deployment_method', sa.String(), nullable=True),
        sa.Column('flow_version', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('NOW()')),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('NOW()')),
        sa.PrimaryKeyConstraint('workflow_id'),
        sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.template_id'], name='fk_workflows_template_id'),
        schema='public'
    )
    
    # Create indexes for workflow_templates
    op.create_index('idx_templates_scope', 'workflow_templates', ['scope'], schema='public')
    op.create_index('idx_templates_tenant', 'workflow_templates', ['tenant_id'], schema='public')
    op.create_index('idx_templates_category', 'workflow_templates', ['category'], schema='public')
    op.create_index('idx_templates_status', 'workflow_templates', ['status'], schema='public')
    op.create_index('idx_templates_based_on', 'workflow_templates', ['based_on'], schema='public')
    op.create_index('idx_templates_featured', 'workflow_templates', ['is_featured'], 
                   postgresql_where=sa.text('is_featured = true'), schema='public')
    
    # Create indexes for template_versions
    op.create_index('idx_template_versions_template', 'template_versions', ['template_id'], schema='public')
    op.create_index('idx_template_versions_current', 'template_versions', ['template_id'], 
                   postgresql_where=sa.text('is_current = true'), schema='public')
    
    # Create indexes for template_usage
    op.create_index('idx_template_usage_template', 'template_usage', ['template_id'], schema='public')
    op.create_index('idx_template_usage_tenant', 'template_usage', ['tenant_id'], schema='public')
    op.create_index('idx_template_usage_action', 'template_usage', ['action'], schema='public')
    
    # Create indexes for workflows
    op.create_index('idx_workflows_tenant', 'workflows', ['tenant_id'], schema='public')
    op.create_index('idx_workflows_template', 'workflows', ['template_id'], schema='public')
    op.create_index('idx_workflows_status', 'workflows', ['status'], schema='public')
    op.create_index('idx_workflows_tags', 'workflows', ['tags'], postgresql_using='gin', schema='public')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop workflow template system
    op.drop_index('idx_workflows_tags', 'workflows', schema='public')
    op.drop_index('idx_workflows_status', 'workflows', schema='public') 
    op.drop_index('idx_workflows_template', 'workflows', schema='public')
    op.drop_index('idx_workflows_tenant', 'workflows', schema='public')
    op.drop_table('workflows', schema='public')
    
    op.drop_index('idx_template_usage_action', 'template_usage', schema='public')
    op.drop_index('idx_template_usage_tenant', 'template_usage', schema='public')
    op.drop_index('idx_template_usage_template', 'template_usage', schema='public')
    op.drop_table('template_usage', schema='public')
    
    op.drop_index('idx_template_versions_current', 'template_versions', schema='public')
    op.drop_index('idx_template_versions_template', 'template_versions', schema='public')
    op.drop_table('template_versions', schema='public')
    
    op.drop_index('idx_templates_featured', 'workflow_templates', schema='public')
    op.drop_index('idx_templates_based_on', 'workflow_templates', schema='public')
    op.drop_index('idx_templates_status', 'workflow_templates', schema='public')
    op.drop_index('idx_templates_category', 'workflow_templates', schema='public')
    op.drop_index('idx_templates_tenant', 'workflow_templates', schema='public')
    op.drop_index('idx_templates_scope', 'workflow_templates', schema='public')
    op.drop_table('workflow_templates', schema='public')
    
    # Restore old trading partner/profile system
    op.add_column('validation_transactions', sa.Column('source_partner_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='public')
    op.add_column('validation_transactions', sa.Column('partner_profile_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='public')
    op.create_foreign_key(op.f('validation_transactions_partner_profile_id_fkey'), 'validation_transactions', 'partner_profiles', ['partner_profile_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('validation_transactions_source_partner_id_fkey'), 'validation_transactions', 'trading_partners', ['source_partner_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('processing_logs', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='public')
    op.create_foreign_key(op.f('fk_processing_logs_profile_id'), 'processing_logs', 'partner_profiles', ['profile_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_table('partner_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snip_level_enabled', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('validation_schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('snip_level', sa.VARCHAR(length=10), server_default=sa.text("'SNIP3'::character varying"), autoincrement=False, nullable=False),
    sa.Column('generate_ta1', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('generate_999', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('custom_validation_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('file_name_patterns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['public.trading_partners.id'], name=op.f('partner_profiles_partner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('partner_profiles_pkey')),
    schema='public'
    )
    op.create_index(op.f('ix_public_partner_profiles_validation_schema_name'), 'partner_profiles', ['validation_schema_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_partner_profiles_tenant_id'), 'partner_profiles', ['tenant_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_partner_profiles_id'), 'partner_profiles', ['id'], unique=False, schema='public')
    op.create_table('trading_partners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sftp_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('sftp_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trading_partners_pkey')),
    sa.UniqueConstraint('sftp_username', name=op.f('trading_partners_sftp_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('_tenant_partner_name_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='public'
    )
    op.create_index(op.f('ix_public_trading_partners_tenant_id'), 'trading_partners', ['tenant_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_trading_partners_name'), 'trading_partners', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_trading_partners_id'), 'trading_partners', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###
